#include<iostream>
#include"head.h"
using namespace std;

extern short now[][9];
extern short available[][9];
extern short record[][9][9];
extern int turns;

void print_board(int a)//¥Ú”°∆Â≈Ã
{
	cout<<endl<<"*********ª∂”≠¿¥µΩ∫⁄∞◊∆Â”Œœ∑*********"<<endl;
	cout<<"*****************";
	if(turns<10)
		cout<<"0";
	cout<<turns;
	cout<<"*****************"<<endl;
	legal_moves();
	short court[18][18]={0};
	int i=0,j=0;
	int letter=21;
	for(i=2;i<18;i+=2)
		court[0][i]=letter++;
	letter=11;
	for(i=2;i<18;i+=2)
		court[i][0]=letter++;
	for(i=3;i<18;i+=2)
	{
		for(j=3;j<18;j+=2)
			court[i][j]=197;
	}
	for(i=1;i<18;i+=2)
	{
		for(j=2;j<18;j+=2)
			court[i][j]=196;
	}
	for(i=2;i<18;i+=2)
	{
		for(j=1;j<18;j+=2)
			court[i][j]=179;
	}
	for(i=3;i<18;i+=2)
		court[1][i]=194;
	for(i=3;i<18;i+=2)
		court[17][i]=193;
	for(i=3;i<18;i+=2)
		court[i][1]=195;
	for(i=3;i<18;i+=2)
		court[i][17]=180;
	court[1][1]=218;
	court[1][17]=191;
	court[17][1]=192;
	court[17][17]=217;
	for(i=1;i<9;i++)
	{
		for(j=1;j<9;j++)
		{
			if(now[i][j]==1)
				court[2*i][2*j]=1;
			if(now[i][j]==2)
				court[2*i][2*j]=2;
			if(available[i][j]!=0)
				court[2*i][2*j]=available[i][j];
			if(now[i][j]==4)
				court[2*i][2*j]=4;
		}
	}
	char temp='a';
	for(i=0;i<18;i++)
	{
		for(j=0;j<18;j++)
		{
			if(court[i][j]==0)
				cout<<"  ";
			if(court[i][j]==1)
				cout<<"°Ò ";
			if(court[i][j]==2)
				cout<<"° ";
			if(court[i][j]==4)
			{
				if(a==2)
					cout<<"££";
				else
					cout<<"  ";
			}
			if(court[i][j]==11)
				cout<<"£±";
			if(court[i][j]==12)
				cout<<"£≤";
			if(court[i][j]==13)
				cout<<"£≥";
			if(court[i][j]==14)
				cout<<"£¥";
			if(court[i][j]==15)
				cout<<"£µ";
			if(court[i][j]==16)
				cout<<"£∂";
			if(court[i][j]==17)
				cout<<"£∑";
			if(court[i][j]==18)
				cout<<"£∏";
			if(court[i][j]==21)
				cout<<"£·";
			if(court[i][j]==22)
				cout<<"£‚";
			if(court[i][j]==23)
				cout<<"£„";
			if(court[i][j]==24)
				cout<<"£‰";
			if(court[i][j]==25)
				cout<<"£Â";
			if(court[i][j]==26)
				cout<<"£Ê";
			if(court[i][j]==27)
				cout<<"£Á";
			if(court[i][j]==28)
				cout<<"£Ë";
			if(court[i][j]==31)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£¡\033[0m";
			}
			if(court[i][j]==32)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£¬\033[0m";
			}
			if(court[i][j]==33)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£√\033[0m";
			}
			if(court[i][j]==34)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£ƒ\033[0m";
			}
			if(court[i][j]==35)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£≈\033[0m";
			}
			if(court[i][j]==36)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£∆\033[0m";
			}
			if(court[i][j]==37)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£«\033[0m";
			}
			if(court[i][j]==38)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£»\033[0m";
			}
			if(court[i][j]==39)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£…\033[0m";
			}
			if(court[i][j]==40)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£ \033[0m";
			}
			if(court[i][j]==41)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£À\033[0m";
			}
			if(court[i][j]==42)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£Ã\033[0m";
			}
			if(court[i][j]==43)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£Õ\033[0m";
			}
			if(court[i][j]==44)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£Œ\033[0m";
			}
			if(court[i][j]==45)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£œ\033[0m";
			}
			if(court[i][j]==46)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£–\033[0m";
			}
			if(court[i][j]==47)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£—\033[0m";
			}
			if(court[i][j]==48)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£“\033[0m";
			}
			if(court[i][j]==49)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£”\033[0m";
			}
			if(court[i][j]==50)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£‘\033[0m";
			}
			if(court[i][j]==51)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£’\033[0m";
			}
			if(court[i][j]==52)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£÷\033[0m";
			}
			if(court[i][j]==53)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£◊\033[0m";
			}
			if(court[i][j]==54)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£ÿ\033[0m";
			}
			if(court[i][j]==55)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£Ÿ\033[0m";
			}
			if(court[i][j]==56)
			{
				if(a==3)
					cout<<"££";
				else
					cout<<"\033[32m£⁄\033[0m";
			}
			if((court[i][j]>56)&&(court[i][j]<90))
				cout<<"££";
			if(court[i][j]==179)
				cout<<"©¶ ";
			if(court[i][j]==180)
				cout<<"©» ";
			if(court[i][j]==191)
				cout<<"©¥ ";
			if(court[i][j]==192)
				cout<<"©∏©§";
			if(court[i][j]==193)
				cout<<"©ÿ©§";
			if(court[i][j]==194) 
				cout<<"©–©§";
			if(court[i][j]==195)
				cout<<"©¿©§";
			if(court[i][j]==196)
				cout<<"©§©§";
			if(court[i][j]==197)
				cout<<"©‡©§";
			if(court[i][j]==217)
				cout<<"©º ";
			if(court[i][j]==218)
				cout<<"©∞©§";
		}
		cout<<endl;
	}
	int cb=0,cw=0;
	cb=count();
	cw=cb%100;
	cb=cb/100;
	cout<<"∫⁄∑Ω ";
	if(cb<10)
		cout<<"0";
	cout<<cb;
	cout<<"                      ";
	if(cw<10)
		cout<<"0";
	cout<<cw;
	cout<<" ∞◊∑Ω"<<endl;
	cout<<"************************************"<<endl;
}